drop table Compte;
/*drop table LienFastaElectro;
drop table lienPCRFasta;
drop table lienqPCRFasta;*/
drop table qPCR;
drop table PCR;
/*drop table Fasta;
drop table Electrophoregramme;*/
drop table CorrespondanceGeneBacterie;
drop table Gene;
drop table Bacterie;
drop table Individu;
drop table Taxonomie;
drop table Personne;
drop table Piege;
drop table Site;
drop table Grotte;
drop table SystemeHydrographique;
drop table EquipeSpeleo;
